# Generated by Django 2.1.1 on 2018-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('your_email', models.EmailField(blank=True, max_length=254)),
                ('your_message', models.CharField(max_length=2000)),
                ('your_feedback_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
