# Generated by Django 2.1.1 on 2018-10-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_date', models.DateTimeField(auto_now_add=True)),
                ('answer_edited_date', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField()),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('asked_date', models.DateTimeField(auto_now_add=True)),
                ('question_edited_date', models.DateTimeField(auto_now=True)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qna.Questions')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='answered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qna.Questions'),
        ),
    ]
